name: Build
on:
  - push
  - pull_request

jobs:
  natives-linux-windows:
    name: Linux (x86/ARM/PPC) and Windows native library compilation
    runs-on: ubuntu-latest
    env:
      # The simplest way to produce a library with a low minimum glibc version
      # requirement is to build in an environment having an old glibc. Not only
      # does Ubuntu 18.04 have a fairly old glibc (v2.27), but the symbol
      # versions our library links against require only glibc v2.7 (on x86_64;
      # somewhat higher for some of the other architectures).
      CONTAINER: docker.io/library/ubuntu:18.04
      GCC: gcc-8

    steps:
      - name: Checkout the target branch
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 8
          # Don't need the dependency cache here (or in any of the other native
          # library compilation steps), because we're not invoking the Java
          # compiler in this step. We only need the JDK for its headers.

      # We'll perform the compilation in our own explicitly-managed container
      # rather than specifying a container.image for the job. This is because
      # JavaScript-based actions (actions/checkout, actions/setup-java, etc.)
      # run inside the job container, which breaks on older containers
      # (https://github.com/actions/runner/issues/2906: the actions' runtime is
      # volume-mounted into the container, but that runtime is dynamically
      # linked to a higher glibc version than the container ships). Managing
      # the container ourselves lets us use as obsolete an image as we like
      # without impacting our ability to use up-to-date actions.
      - name: Create the compilation container
        run: |
          podman run \
            --name build \
            --replace \
            --tty \
            --detach \
            --env GCC \
            --env JAVA_HOME \
            --network host \
            --volume $(pwd):/workdir \
            --volume $JAVA_HOME:$JAVA_HOME:ro \
            --workdir /workdir/src/main/c \
            $CONTAINER

      - name: Install build prerequisites
        run: |
          podman container exec build apt-get update
          podman container exec build apt-get --assume-yes install make $GCC
          podman container exec build make crosstools

      - name: Build the Linux and Windows native libraries
        run: |
          podman container exec build make clean-linux clean-windows
          podman container exec build make linux windows

      # The names of the artifacts containing native libraries correspond
      # exactly to the directories inside `src/main/c/resources/native`. That
      # way, the Java build job can pull down all artifacts and unpack them
      # into that directory to overwrite the versions in-repo. This is sadly
      # necessary because the actions/download-artifact@v6 action flattens
      # paths inside artifacts. If it retained full relative paths, we could
      # put Linux and Windows natives inside the same artifact, and we could be
      # flexible with the artifact names. But it doesn't, so we can't, and we
      # can't.
      - name: Upload Linux native libraries
        uses: actions/upload-artifact@v7
        with:
          name: linux
          path: src/main/c/resources/native/linux

      - name: Upload Windows native libraries
        uses: actions/upload-artifact@v7
        with:
          name: windows
          path: src/main/c/resources/native/windows

  natives-macos:
    name: macOS native library compilation
    runs-on: macos-latest

    steps:
      - name: Checkout the target branch
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: zulu
          java-version: 8

      - name: Build the macOS native libraries
        working-directory: src/main/c
        run: |
          make clean-osx
          make osx

      - name: Upload macOS native libraries
        uses: actions/upload-artifact@v7
        with:
          name: osx
          path: src/main/c/resources/native/osx/libNRJavaSerial.jnilib

  natives-freebsd:
    name: FreeBSD native library compilation
    runs-on: ubuntu-latest
    env:
      CONTAINER: docker.io/empterdose/freebsd-cross-build:11.4

    steps:
      - name: Checkout the target branch
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 8

      - name: Fake the FreeBSD Java headers
        # This feels extremely dirty, but the only native header we care about
        # is `jni_md.h`, and it is exactly identical between Linux and FreeBSD
        # (at least in OpenJDK 8).
        run: |
          ln -s $JAVA_HOME/include/linux $JAVA_HOME/include/freebsd

      - name: Create the compilation container
        run: |
          podman run \
            --name build \
            --replace \
            --tty \
            --detach \
            --env JAVA_HOME \
            --network host \
            --volume $(pwd):/workdir \
            --volume $JAVA_HOME:$JAVA_HOME:ro \
            --workdir /workdir/src/main/c \
            $CONTAINER

      - name: Build the FreeBSD native libraries
        run: |
          podman container exec build pwd
          podman container exec build ls -alh
          podman container exec build make clean-freebsd
          podman container exec build settarget i386-freebsd11 make freebsd32
          podman container exec build settarget x86_64-freebsd11 make freebsd64
          podman container exec build settarget arm64-freebsd11 make freebsdarm64v8

      - name: Upload FreeBSD native libraries
        uses: actions/upload-artifact@v7
        with:
          name: freebsd
          path: src/main/c/resources/native/freebsd

  java:
    name: Java compilation
    runs-on: ubuntu-latest

    needs:
      - natives-linux-windows
      - natives-macos
      - natives-freebsd

    steps:
      # We use Spotless in “ratchet mode” to incrementally enforce code
      # formatting throughout the project. In order to ensure feature branches
      # don't regress formatting when compared with the master branch, we need
      # to have a local copy of the master branch for comparison.
      - name: Checkout the master branch
        uses: actions/checkout@v7
        with:
          ref: master

      - name: Checkout the target branch
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 8
          cache: gradle

      - name: Download native libraries
        uses: actions/download-artifact@v8
        with:
          path: src/main/c/resources/native

      - name: Build the Java library
        run: ./gradlew build

      - name: Determine commit hash for artifact filename
        id: vars
        run: echo "short-rev=$(git rev-parse --short HEAD)" >>$GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: nrjavaserial-${{steps.vars.outputs.short-rev}}
          path: build/libs/*.jar
